// Functions

def ConcatState(Stage,State) {
    SUMMARY_STATE="${SUMMARY_STATE}  STAGE: ${Stage} - ${State}\n"
}

def mailNotification() {
    step([$class: 'Mailer',
          notifyEveryUnstableBuild: true,
          recipients: "root@localhost",
          sendToIndividuals: true])
}

def clearContentUnix() {
    cleanWs()
}

def archiveArtifacts(pattern) {
    step([$class: 'ArtifactArchiver', artifacts: pattern, fingerprint: true, onlyIfSuccessful: false])
}

def DiscordSetHook() {
    if ( currentBuild.result == "SUCCESS" ) {
        return "diskord-jenkins-report"
    } else {
        return "diskord-jenkins-report"
    }
}

def print_info_header(message) {
    echo "#---------------------------------------"
    echo "#---> ${message}"
    echo "#---------------------------------------"
}

def DockerRunner(cmd, logfile){
    cmd_docker = "sudo docker exec --tty -u \$(id -u) ${BASE_CONTAINER_NAME} bash -c "
    cmd_prefix = "\' cd ${CONTAINER_PROJECT_ROOT} && "
    cmd_postfix = " 2>&1 | tee ${CONTAINER_PROJECT_ROOT}/artifacts/${logfile}; exit \${PIPESTATUS[0]}\'"
    sh "${cmd_docker} ${cmd_prefix} ${cmd} ${cmd_postfix}"
}


pipeline    {
    agent { node { label "${BUILD_HOST}"} }
    options { ansiColor('xterm') }
    environment {
        LAST_STAGE_NAME = ""
        SUMMARY_STATE="PROJECT: ${currentBuild.fullDisplayName}\n.   BRANCH: ${SRC_BRANCH}\n. COMMENT: ${BUILD_COMMENT}\n\n"
        BUILD_OPTS = " "
    }

    stages {
        stage('Grab SCM') {
            steps {
                script {
                    LAST_STAGE_NAME="${STAGE_NAME}"
                    clearContentUnix()
                    checkout scm
                    sh "mkdir -p artifacts"
                    ConcatState(LAST_STAGE_NAME,"OK")
                }
            }
        }

        stage('Building yiot tools Docker image') {
            steps {
                script {
                    LAST_STAGE_NAME="${STAGE_NAME}"
                    print_info_header("${STAGE_NAME}")   
               	    sh "iotkit/sdk/scripts/pkg/virgil-iotkit-tools-docker.sh 2>&1 | tee -a ${workspace}/artifacts/build-image.log; exit \${PIPESTATUS[0]}"
                    ConcatState(LAST_STAGE_NAME,"OK")                    
                }
            }
        }

        stage('Upload image') {
            steps {
                script {
                    LAST_STAGE_NAME="${STAGE_NAME}"
                    if ( UPLOAD_IMAGE == "true" ) {
                	print_info_header("${STAGE_NAME}")   
                	withCredentials([usernamePassword(credentialsId: 'docker-registry', passwordVariable: 'CI_PASSWORD', usernameVariable: 'CI_USERNAME')]) {
                	  sh "sudo docker login -u \${CI_USERNAME} -p \${CI_PASSWORD}"
                        }
                	sh "iotkit/sdk/scripts/pkg/virgil-iotkit-tools-docker-push.sh 2>&1 | tee -a ${workspace}/artifacts/upload-image.log; exit \${PIPESTATUS[0]}"
                	ConcatState(LAST_STAGE_NAME,"OK")                    
                    } else  {
			ConcatState(LAST_STAGE_NAME,"SKIPPED")
                    }
                }
            }
        }

        stage('Archive artifacts') {
            steps {
                script {
                    LAST_STAGE_NAME="${STAGE_NAME}"
                    print_info_header("${LAST_STAGE_NAME}")
                    writeFile file: 'artifacts/summary.log', text: "${SUMMARY_STATE}"
                    archiveArtifacts('artifacts/**/*')
                    ConcatState(LAST_STAGE_NAME,"OK")                    
                }
            }
        }

    }

////
//// Post procedure
////

    post {
        always {
            print_info_header("Report")
            script {
                // Send message to Discord
                if ( DISKORD_NOTIFY == "true" ) {
                    try {
                        withCredentials([string(credentialsId: DiscordSetHook(), variable: 'WEBHOOK')]) {
                            discordSend description: SUMMARY_STATE,
                                    footer: 'Job state: ' + currentBuild.currentResult,
                                    link: env.BUILD_URL,
                                    result: currentBuild.currentResult,
                                    title: JOB_NAME,
                                    webhookURL: WEBHOOK
                        }
                    } catch(any) { }
                }
            }
            echo "#---- SUMMARY RESULTS OF TESTS ---------"
            echo "# ${SUMMARY_STATE}"
            echo "#---------------------------------------"
        }
        success {
            echo 'POST SUCCESS'
        }
        unstable {
            echo 'POST UNSTABLE'
        }
        failure {
            echo 'POST FAILURE'
            ConcatState(LAST_STAGE_NAME,"FAILURE")
        }
        changed {
            echo 'POST CHANGED'
        }
    }
}
